# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter build debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          channel: stable
      - uses: actions/checkout@v2
      - name: Build project for Windows
        run: flutter build windows -v --debug
      - name: List files
        run: cmd /r dir /b /s build\\windows\\runner\\Debug
      - name: Output
        uses: actions/upload-artifact@v2
        with:
          name: flutter-windows-debug
          path: build/windows/runner/Debug
  android-build:
    # needs: windows-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          channel: stable
      - uses: actions/checkout@v2
      - name: Build apk
        run: flutter build apk -v --debug
      - name: Store APK
        uses: actions/upload-artifact@v2
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
  linux-build:
    runs-on: ubuntu-latest
    # needs: windows-build
    steps:
      - name: Install ninja
        run: sudo apt update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
      - name: Configuration flutter
        run: flutter config --enable-linux-desktop
      - uses: actions/checkout@v2
      - name: Build project for Linux
        run: flutter build linux -v --debug
      - name: Build package
        run: |
          find build/linux/x64/debug/bundle -type f
          tar -zcvf build/flutter-linux-debug.tar.gz -C build/linux/x64/debug/bundle .

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: flutter test
      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: flutter-linux-debug.tar.gz
          path: build/flutter-linux-debug.tar.gz
